### ISSUE TITLE
Evidence code for "self-reported"

### ISSUE THREAD

**Issue by daniwelter** [evidenceontology/evidenceontology#136] opened 2017-05-08 16:16 UTC
The GWAS Catalog (http://www.ebi.ac.uk/gwas/) is in the process of mapping ancestry determination methods used in the GWA studies to ECO evidence codes. We have managed to map most of the concepts we need but haven't been able to find a suitable evidence code to capture self-reported ancestry (ie each study participant self-reports their ancestry and this is taken at face-value in the analysis). Would it be possible to add an evidence code for this, please?

**Comment by jbmunro** [comment] 2017-05-17 15:24
Hi and thank you for the request.  

We will create "self-reported ancestry evidence" soon - possibly with the next release of ECO.  This term will have a stable ID, but the parentage may change, as we are currently revamping statement evidence and related terminology. 

If you are willing to share a list of your current successful mappings, we would love to see it.  (We maintain a similar type of mapping for GAF/ECO codes https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt)

James

**Comment by daniwelter** [comment] 2017-05-19 09:40
Hi James,

Thank you for getting back to me. Our mappings so far are
GWAS Category	ECO term	URI
Self-reported	    traceable author statement used in manual assertion	http://purl.obolibrary.org/obo/ECO_0000304
Genetically determined	genetic similarity evidence used in manual assertion	http://purl.obolibrary.org/obo/ECO_0000253
Inference of ancestry from country of recruitment	inference from background scientific knowledge used in manual assertion	http://purl.obolibrary.org/obo/ECO_0000306
Inference of ancestry from other information	curator inference used in manual assertion	http://purl.obolibrary.org/obo/ECO_0000305
Method of ancestry ascertainment not reported	non-traceable author statement or non-traceable author statement used in manual assertion	http://purl.obolibrary.org/obo/ECO_0000034 or http://purl.obolibrary.org/obo/ECO_0000303

I would appreciate your thoughts on whether we have mapped to the most appropriate term in each case or whether a better term is available.

Best wishes
Dani Welter, PhD
Ontologist/Bioinformatician
Samples, Phenotypes and Ontologies Team
---------------------------------------
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
Tel: +44 (0) 1223 492 502

**Comment by jbmunro** [comment] 2017-06-06 16:52
Hi Dani,

We have discussed your mapping internally. Your mapping appears to be based on similarity to our ECO labels, but our definitions are too restrictive for your suggested mapping. It looks like we may either need to create new terms or redefine some current terms to meet your needs.  

For example, GWAS 'self-reported' does not map to ECO traceable author statement used in manual assertion'. 'traceable author statement used in manual assertion' is a child of 'traceable author statement', which is defined as "A type of author statement that is based on a cited reference."  Assuming that 'self-reported' does not indicate an author's statement based on a cited reference, this would be a mapping that does not work. In this particular case, I may have a solution: we are creating several new terms such as 'self-reported information evidence' and 'self-reported ancestry evidence'.

However, to resolve the other mappings I will need some further information from you. (Please see our "New term request how to" at https://github.com/evidenceontology/evidenceontology/wiki/New-term-request-how-to). Ideally, the following information would be helpful:

1) Specific definitions for your GWAS terms.  For example, what do you mean by "self-reported"?  What is being self-reported?  Who is reporting this? Or in the case of "genetically determined", what is being genetically determined?

2) Specific examples of annotations where you map the GWAS terms and ECO categories so that I might better understand the context.

Thanks,

James

**Comment by jbmunro** [comment] 2018-02-08 18:34
Hi Dani,

I am curious to know if you wish to move forward with the term requests.

James

**Comment by daniwelter** [comment] 2018-02-09 17:15
Hi James,
I left the GWAS project a few months ago so I don't know where they're at with this work.
@twhetzel @tburdett would you be able to comment?
Thanks
Dani

**Comment by twhetzel** [comment] 2018-02-12 11:44
I'll check-in with @tburdett on this and report back.

**Comment by jbmunro** [comment] 2018-02-12 14:24
Thanks!

James

**Comment by jbmunro** [comment] 2018-08-02 14:03
Hi @twhetzel and @tburdett,
Given that there has been no further follow-up to this ticket, I am closing it.  Please feel free to re-open the ticket if the need arises.
James

**Comment by PabloBotas** [comment] 2020-04-02 14:37
Hi, I was wondering if there is any modifier or term applicable when evidence of a given feature is provided by a patient. We are adopting this ontology in a rare diseases diagnosis support platform (www.dx29.ai) and some of the evidence is provided by the patient directly. It would be useful to be able to distinguish evidence provided by the patient from that confirmed by a physician.

I guess both concepts are very related to ECO:0000303. Is there a way to distinguish the level of evidence one provides from the other currently? Would this be within the scope of the ontology?

This is related to the current issue. Would you consider re-opening it and expanding the scope to other self-reported items, such as symptoms?

**Comment by mgiglio99** [comment] 2020-04-02 17:58
Hi, I have reopened this issue. We are happy to look into your question. We'll get back to you soon with some thoughts.
Michelle

**Comment by PabloBotas** [comment] 2020-05-15 14:56
Hi everyone! How is this issue going? Any news to share?
Thanks!

**Comment by mgiglio99** [comment] 2020-05-18 15:46
Hi @PabloBotas 
Sorry for the delay on this.

We propose the following:
We will create a parent term for 'author statement' ECO:0000204 that will be:
new term
name: documented statement evidence 
def: A type of evidence in which information is recorded in some documentation system, for example, but not limited to a publication, survey, or medical record.

This new term will have two additional children:
new term
name: medical practitioner statement evidence
def: A type of documented statement evidence in which information is stated by a health care professional, for example, but not limited to a doctor, nurse, or psychologist.

new term
name: self-reported statement evidence
def: A type of documented statement evidence in which information is stated by an individual and becomes part of a documented record.
synonym: self-reported patient evidence

(We've also noticed some problems with the current structure of children of 'author statement' which we will deal with in a separate issue.)

Also, could you tell us which project or ontology you are working with, so we can make sure to document who requested the term and capture that group on our user list.

Regards,
Michelle

**Comment by PabloBotas** [comment] 2020-05-19 11:27
Hi Michelle!
Yes, I think this is a good approach. I would however change the "self-reported" term to "patient-reported". My point is that "self" depends on the user, while patient does not. Was this something you considered?

Best,
Pablo

**Comment by mgiglio99** [comment] 2020-06-03 15:50
Hi Pablo,

Apologies again for the delay in replying.
We've tried to revise the definition of the previously suggested self-reported term to clarify that we meant it to be inclusive of whatever user is capturing the information and that the only restriction is that the information is coming from a particular individual. We have also suggested a new child term for 'self-reported patient statement evidence', instead of having it as a synonym to the original term as we originally suggested. 
Does this work for you?

revision of def for new term:
name: self-reported individual's statement evidence
def: A type of documented statement evidence in which information is provided by an individual through means including, but not limited to, paper form, electronic form, or verbal communication, and is captured in a documented record.

new child term of above term:
name: self-reported patient statement evidence
def: A type of self-reported statement evidence in which information is provided by a patient in a clinical setting.

**Comment by mgiglio99** [comment] 2020-06-22 17:12
Hi @PabloBotas 
Just checking if you had a chance to look at our revised suggestions.
Thanks
Michelle

**Comment by PabloBotas** [comment] 2020-06-24 17:04
Hi @mgiglio99 ,
Sorry for the delay answering! Yes, I think this is very good and completely fits our purposes. So I would close the issue as Done.

On a separate (somewhat parallel) issue: do you think this will force you to slowly implement other subtypes? I can see this potentially forcing you to create a "self-reported tutor statement evidence", then a "parent", then... etc. Is this fear of mine shared? Do you see a way of solving this?

In any case, many thanks!!

**Comment by mgiglio99** [comment] 2020-06-24 17:41
Hi @PabloBotas 
Glad to hear these terms will work. We will make them and push out a new release.
Regarding the term expansion you mention, I'm a bit worried that might happen, but if it does, we'll figure something out then.  :)
Also, could you tell us which project or ontology you are working with, so we can make sure to document the group that requested the term and capture that group on our user list?
Thanks very much,
Michelle

**Comment by PabloBotas** [comment] 2020-06-25 07:18
Hi,
Yes, I am writing from Foundation 29 of February regarding the [Dx29](www.dx29.ai) project. We work with HPO and MONDO, which means that we work indirectly with ORDO and GO among others that through MONDO we also consider but I do not recall now explicitly.

What other information do you need?

Thanks!
Pablo

**Comment by nsuvarnaiari** [comment] 2020-06-26 19:56
Hi @PabloBotas ,

Thanks for sharing the details about your project.
All the suggested terms (including self-reported patient statement evidence - ECO:0006154) have been added. The latest release of ECO contains all the terms.
-evidence
     - documented statement evidence (ECO:0006151)
            -author statement evidence (ECO:0000204)
            -medical practitioner statement evidence (ECO:0006152)
            -self-reported individual's statement evidence (ECO:0006153)
                      -self-reported patient statement evidence (ECO:0006154)

Closing the ticket but please reopen if needed. 

Thanks,
Suvvi

**Comment by mgiglio99** [comment] 2021-09-06 21:58
@PabloBotas 
We are updating the list of users on the ECO web page. We'd like to list Foundation 29.
Is it ok if we use a screen shot of the logo from your website? (The square with the 29 overlapping it and the Foundation Twenty-nine text to the right.)
Totally fine if not.
Thanks,
Michelle

**Comment by PabloBotas** [comment] 2021-09-07 07:42
Hi, yes, it is fine. You can take this image directly
![Logo](https://user-images.githubusercontent.com/12137767/132304736-c4f1179e-08bc-4d49-a73a-4e1cf8cb32a3.png)

**Comment by mgiglio99** [comment] 2021-09-07 13:56
Thanks so much!
: )

**Comment by mgiglio99** [comment] 2022-09-09 20:02
Hello @twhetzel , @tburdett 
In reviewing this issue, we realized that we promised a term that didn't end up getting made due to the issue getting off on a tangent.
We are now making this new term:
name: 'self-reported ancestry evidence'
def: A type of self-reported individual's statement evidence in which a person reports their ancestry and that information is taken at face value.
parent: 'self-reported individual's statement evidence' ECO:0006153

Please let us know if this looks ok to you. We will proceed with adding it in the next ECO release.

**Comment by daniwelter** [comment] 2022-09-12 06:27
Hi @mgiglio99, the Human Ancestry Ontology would be interested in this term as well and the definition matches our needs. I can't speak for the present requirements of the GWAS Catalog but your suggested new term is also in line with what I expected from my original request.

**Comment by mgiglio99** [comment] 2023-01-06 00:29
Thanks @daniwelter.
Missed this one for the last release. It will go in the next one.
Michelle and @nsuvarnaiari

**Comment by mgiglio99** [comment] 2023-01-09 19:29
This term went was in the October 2022 release.
ECO:0006395

**Closed by mgiglio99** 2023-01-09 19:29 UTC
